# Generated by Django 3.2.7 on 2021-10-03 07:09

import apps.card_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0004_remove_card_profile_test_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.card_profile.models.Card_profile.path_and_rename),
        ),
    ]
