# Generated by Django 3.2.7 on 2021-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0005_alter_card_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
        ),
    ]
