# Generated by Django 3.2.7 on 2021-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_profile', '0006_card_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
    ]
